### ISSUE TITLE
Opsworks no longer creates database.yml for Rails applications without MySQL Layer in Opsworks

### ISSUE THREAD

**Issue by mfrister** [aws/opsworks-cookbooks#100]
We're using RDS and are setting our database configuration in the custom Stack JSON.

Until recently Opsworks generated a database.yml for our Rails application, but now it seems to only do this when a database server is set up via an Opsworks Layer. I found the following code in the Opsworks deploy cookbook (on the server, this version seems to be unpublished on GitHub):

``` ruby
template "#{node[:deploy][application][:deploy_to]}/shared/config/database.yml" do
  cookbook "rails"
  source "database.yml.erb"
  mode "0660"
  owner node[:deploy][application][:user]
  group node[:deploy][application][:group]
  variables(
    :database => node[:deploy][application][:database],
    :environment => node[:deploy][application][:rails_env]
  )

  only_if do
    node[:opsworks][:layers].has_key?('db-master')
  end
end.run_action(:create)
```

The [same part of the currently published version](https://github.com/aws/opsworks-cookbooks/blob/87d2084650a3bf35e3816c0ce0755c9121de5d26/deploy/definitions/opsworks_deploy.rb#L110) does not contain the `only_if` block.

This way of configuring a Rails application with a non-Opsworks database server is [explicitly documented in the Opsworks docs](http://docs.aws.amazon.com/opsworks/latest/userguide/workinglayers-rails.html#workinglayers-rails-db), so I think you should revert this change.

By the way, publishing the Opsworks cookbooks when deploying a new version would be great, otherwise they're not much help when debugging problems like this.

**Comment by rgalite** [comment]
I thought I was the only one. Thanks for reporting this.

**Comment by githuesch** [comment]
We will not revert it, but we will replace it with something more appropriate. Instead of 

`node[:opsworks][:layers].has_key?('db-master')`
there is now `deploy[:database][:host].present?`, and that will be rolled out soon.

Please note that you don't need a db-master instance, you only need the layer. So adding an empty db-master layer should do the trick for you right now, without changing anything in your cookbooks.

As for cookbooks on Github, we will soon change the way customers can follow our changes. There will be one branch that reflects the current state you will see on running instances, and another branch that reflects the next version of our agent.

**Comment by mfrister** [comment]
@githuesch Thanks for the fast reply and the workaround! Your proposed changes for the database and the cookbooks sound great.

**Comment by mrclmrvn** [comment]
I'm experiencing this too. Thanks for the report, and the suggested workaround. Haven't tried it though.

**Comment by heffergm** [comment]
So despite the fact that you're no longer creating database.yml (assuming the db-master layer doesn't exist) at some point along the way #{release_path}/config/database.yml is still created as a link to shared/config/database.yml.

My issue is that I'm using a before_migrate hook to link database.yml, and after that runs successfully, my link then gets blown away, which makes everything fail.

If we're not going to create the config, we need to not create the symlink.

**Comment by githuesch** [comment]
We just finished rolling out a fix for this. The workaround should not be needed any longer.

@meeee @RudthMael @mrclmrvn @heffergm Can you try again and let me know if this is still an issue for you?

**Comment by heffergm** [comment]
This is still broken for me. It's creating the symlink to shared/config/database.yml, which isn't what I need (and in any case, it shouldn't create the link at all. I don't want it to do anything but keep its hands off database.yml). My configs aren't kept in shared/config due to all kinds of other chicken/egg problems in getting custom configs in place for a rails app layer. Ultimately I'm going to have to drop using pre-built layers.

**Comment by rgalite** [comment]
It went okay on my side:

``` Bash
[2014-02-10T17:55:22+00:00] INFO: Processing template[/srv/www/myproject/shared/config/database.yml] action create (/opt/aws/opsworks/releases/20140128141631_219/cookbooks/deploy/definitions/opsworks_deploy.rb line 111)
[2014-02-10T17:55:22+00:00] DEBUG: Current content\'s checksum:  
[2014-02-10T17:55:22+00:00] DEBUG: Rendered content\'s checksum: ac5e6b703cc6c24cfe4e1ce81b37a73d1c5e469a21649b4600dafea9680ae586
[2014-02-10T17:55:22+00:00] INFO: template[/srv/www/myproject/shared/config/database.yml] updated content
[2014-02-10T17:55:22+00:00] INFO: template[/srv/www/myproject/shared/config/database.yml] owner changed to 4000
[2014-02-10T17:55:22+00:00] INFO: template[/srv/www/myproject/shared/config/database.yml] group changed to 33
[2014-02-10T17:55:22+00:00] INFO: template[/srv/www/myproject/shared/config/database.yml] mode changed to 660
[2014-02-10T17:55:22+00:00] INFO: deploy[/srv/www/myproject] queueing checkdeploy hook /srv/www/myproject/releases/20140210174919/deploy/before_migrate.rb
[2014-02-10T17:55:22+00:00] INFO: Processing template[/srv/www/myproject/shared/config/database.yml] action create (/opt/aws/opsworks/releases/20140128141631_219/cookbooks/deploy/definitions/opsworks_deploy.rb line 111)
[2014-02-10T17:55:22+00:00] DEBUG: Current content\'s checksum:  ac5e6b703cc6c24cfe4e1ce81b37a73d1c5e469a21649b4600dafea9680ae586
[2014-02-10T17:55:22+00:00] DEBUG: Rendered content\'s checksum: ac5e6b703cc6c24cfe4e1ce81b37a73d1c5e469a21649b4600dafea9680ae586
[2014-02-10T17:55:22+00:00] DEBUG: template[/srv/www/myproject/shared/config/database.yml] content has not changed.
```

**Comment by githuesch** [comment]
@heffergm I think I get it now. We're now making sure that we create the physical file when we have the required data, but the creation of the symlink does not reflect this. So there is always a symlink, which might be a dangling one. Fixing this makes sense, as I don't see how a dangling link would help anyone. But not creating the symlinks at all would break all customers that expect OpsWorks to create them. Would it work for you if the default was still to create links for all the files that exist in shared/config, with an option to turn this off?

**Comment by heffergm** [comment]
That sounds fine.

**Comment by mfrister** [comment]
@githuesch Works again, thanks for the fix!

**Comment by alanpeabody** [comment]
Is this same issue currently effecting memcached.yml? I was not seeing it being created, however after adding an empty memcached layer it is being added (even thought I am overriding the template and using elasticache).

**Comment by githuesch** [comment]
@alanpeabody Yes, exactly. We're on it.

**Comment by rymohr** [comment]
@githuesch Does that mean no more rails console on each instance then?

```
ssh ubuntu@instance
bundle exec rails c production
```

Rails Error: Unable to access log file. Please ensure that [app]/releases/20140402021734/log/production.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.

lib/rails/application/configuration.rb:110:in `database_configuration': Could not load database configuration. No such file - /srv/www/[app]/releases/20140402021734/config/database.yml (RuntimeError)

**Comment by rymohr** [comment]
I noticed that the symlinks were there but the ubuntu user simply didn't have permission to access them. Was able to get around the issue with:

```
sudo -u deploy -s
cd /srv/www/[app] && bundle exec rails c production
```

What's the recommended way to do this now?

**Comment by mrclmrvn** [comment]
@rymohr 

Did you happen to have custom cookbooks? If so, you might want to check any `execute` or `template` block, make sure `owner` and `group` is set to use `deploy[:user]` and `deploy[:group]`.

It defaults to `root`, I believe. I also doubt your app would be able to start with missing/invalid symlink to `database.yml`.

**Comment by jweiss** [comment]
the deploy user was always 'deploy', so in order to use the Rails console you need to either become the 'deploy' user or 'root.

**Comment by mfrister** [comment]
Just noticed I didn't close this issue yet. Everything works for us since a while, so I'm closing now.

**Comment by rymohr** [comment]
@mrclmrvn We have a single custom cookbook for this layer but all it does is install a few packages.  Running `ps aux | grep unicorn` shows it running as `deploy` (which owns the files in `shared/config`) so that explains why the app starts fine.

@jweiss I know for a fact I've never had to `sudo su deploy` to get to the rails console before.  I need to hop in there once every few weeks and this is the first time I've run into this.  Were `read` permissions recently removed for `other` for database.yml by the default cookbook?

**Comment by kstevens** [comment]
@githuesch @alanpeabody We're still seeing the behavior where the shared database.yml is not created (as expected), but OpsWorks still creates a dangling symlink (overwriting our application's database.yml).  What's the fix for this?

**Comment by githuesch** [comment]
@rymohr I don't think we changed any permissions, and I'd be surprised if this worked for you using the ubuntu user. My guess is that you used the Rails console as root instead of as deploy user.

@kstevens As you can see in https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/deploy/definitions/opsworks_deploy.rb#L125-L127, OpsWorks writes the database.yml when a DB host is known. That's the case when you use the built-in db-master layer or when you provide the DB host via custom JSON.

**Comment by kstevens** [comment]
@githuesch I've intentionally left the database.host property out of my custom JSON, so the shared database.yml is not being created, as expected.  However, OpsWorks still overwrites the rails database.yml in /srv/www/appname/current/config with a symlink to /srv/www/appname/shared/config/database.yml (which doesn't exist!).  Separate issue opened here:
https://github.com/aws/opsworks-cookbooks/issues/129

**Comment by githuesch** [comment]
@kstevens I know. As I wrote in an earlier comment, we could change the behavior to only create symlinks for files that actually exist. We just haven't done that yet.

**Comment by kstevens** [comment]
@githuesch That certainly seems preferable to symlinking to non-existent files.  As it stands I don't see a way to deploy with an application's database.yml intact.  Since you haven't implemented it yet, how would I override this behavior with a custom cookbook?

**Comment by githuesch** [comment]
@kstevens You could override the template database.yml.erb so it fits your needs and make sure you always provide at least the host via custom JSON. It doesn't matter if your template actually uses that host. But you still have to provide it to make OpsWorks create the database.yml for you. Would that be viable for now?

**Comment by mmcraedhcu** [comment]
Is there documentation of this in AWS/OpsWorks docs? I'm new to Rails. I included database.yml (which just had some default sqlite3 stuff) in the app I deployed, and now for some reason it's a dead symlink on the instance and apache2 says it cannot read the file. I don't know what to do.

**Comment by jbirdjavi** [comment]
@githuesch Seeing as how there hasn't been any movement on the dangling symlink issue for over a year now, I'm guessing it won't be fixed?  Without overriding the template database.yml file, is there a way to override things to disable the symlink?  I can't figure out where it's symlinking the database.yml file in the Chef recipes.

The reason I ask is because we're transitioning our apps to use environment variables as opposed to custom json.  Since there is a 20kb limit on how much custom json you can put in the stack, it made sense to start moving that direction.

**Comment by githuesch** [comment]
@jbirdjavi config/database.yml and config/memcached.yml are symlinked for Rails apps in general. This is specified in the JSON we send to instances, you won't find this in the cookbooks. I guess overriding the template is still your best shot.

Moving configuration from custom JSON to environment variables due to size constraints sounds odd. Custom JSON is limited to 20KB and we're about to bump this to 80KB. Environment variables are limited to 10KB.

**Comment by jbirdjavi** [comment]
@githuesch Do you know how soon the bump to 80KB will be?  We have a bunch of small apps on a staging stack and keep running into the limit every time we do anything.
