### ISSUE TITLE
Add cache-control: public to nginx for Rails apps

### ISSUE THREAD

**Issue by sudhirj** [aws/opsworks-cookbooks#114]
...because any apps that use asset precompilation will benefit immensely from having the cache-control: public header set on all static assets. These assets will be postfixed with a hash of their contents anyway, so max-age can also be set to a year. 

At the very least, this can be an optional. There's no other way to solve this problem: even with a CDN, changing headers usually isn't allowed, with unnecessarily results in more requests, less speed, and higher costs.

**Comment by glance-** [comment]
This would be immensely appreciated by us too.

**Comment by githuesch** [comment]
If you implement it and open a pull request, I'm happy to review it.

**Comment by chenkirk** [comment]
Not having this feature really impedes the feasibility of using Opsworks to deploy rails app. Without cache-control on assets, [Google PageSpeed Insight](https://developers.google.com/speed/pagespeed/insights/)  will mark your page as slower than it should be, which directly affects the SEO ranking. The fix in #149 seems to have a merge conflict so I am not sure what to do with it.

I am not too good with Chef, would love to help with getting this into main line.

**Comment by chenkirk** [comment]
Tried to fiddle with this in production a bit. I was able to create the proper headers by putting the following code into `unicorn/templates/default/nginx_unicorn_web_app.erb` (recommended from [rails guide](http://guides.rubyonrails.org/asset_pipeline.html#far-future-expires-header)

```
location ~ ^/assets/ {
  expires 1y;
  add_header Cache-Control public;

  add_header ETag "";
  break;
}
```

But to create the pull request I am wondering about a few things. If I simply put it in, that means by default all rails app deployed with opsworks will have the public 1 year cache control. It is probably a good idea because in production rails should be fingerprinting the assets. Would this be a good idea?

**Comment by sainejob** [comment]
+1 - some other option at this point? -- other than manual override of the standard recipe

**Comment by chenkirk** [comment]
@sainejob I thought about creating a new recipe instead of editing the default recipe, but because it is a nginx unicorn config file it makes little sense to edit it after its initial creation.

Maybe we could pester @githuesch on taking a look at the pull request :smirk:

**Comment by kitop** [comment]
+1
The last solution seems like a sane default. Any feedback on what's preventing this from being merged? Happy to help.

**Comment by thomaswitt** [comment]
+1

**Comment by colinyoung** [comment]
I'd also like to see this get merged!

**Comment by jweiss** [comment]
closing as this is a very old issue
