### ISSUE TITLE
App without datasource, deploy/recipes/mysql.rb run anyway

### ISSUE THREAD

**Issue by xavadu** [aws/opsworks-cookbooks#154]
Hello,

Not sure because i am not a ruby programmer, but i believe that is a bug on line 5 here: https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/deploy/recipes/mysql.rb

`next unless deploy[:database]`

should be:

`next unless deploy[:database].nil?`

because deploy[:database] = {} is accepted without the .nil? method, when an app have data source to none

Cheers

**Comment by githuesch** [comment]
`next unless deploy[:database]` means skip to the next iteration of the loop unless we have values to use in this block. So if there is something in deploy[:database], we use it, otherwise we skip.

`next unless deploy[:database].nil?` would turn this behavior around. So when deploy[:data] is actually nil, we would not skip and line 7 (deploy[:database][:username]) would blow up.

**Comment by xavadu** [comment]
i understand that if there are not values in `deploy[:database]` it's block shouldn't be execute, it doesn't happen for me, i select `none` like data source in OpsWorks console and this block get executed anyway.

**Comment by workeitel** [comment]
Thanks for your hint. You're correct `deploy[:database]` is typically not nil but an empty hash. Therefore the creation of the database will fail.

We already fixed this in the current [chef 11.10 branch](https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/deploy/recipes/mysql.rb#L5).
as well as in the [prerelease of 11.4](https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/deploy/recipes/mysql.rb#L5). Only the 9.4 branch is missing, but the changes will be included in the next release.

**Comment by xavadu** [comment]
You are welcome,
Thanks
