### ISSUE TITLE
fetch credentials to download cookbooks from s3 using the IAM role

### ISSUE THREAD

**Issue by jtheuer** [aws/opsworks-cookbooks#208]
It would be a nice improvement if opsworks could use the IAM Role credentials to fetch the cookbook from s3.

**Comment by workeitel** [comment]
We plan to replace s3curl with a better option in the future. Using the IAM roles will then be possible.

**Comment by jtheuer** [comment]
Sounds great. I use the awscli package from amazon do download s3 resources in my cookbooks which can use the instance IAM role, or fall back to a config file in the homedir which is really great for testing stuff with kitchen/vagrant. Maybe it fits for your usecase, too.

**Comment by pghalliday** [comment]
+1

Just converted all my users in my CloudFormation stack to roles and instance profiles. Super annoying that I need to now add a user back so OpsWorks can download cookbooks from S3

**Comment by slobo** [comment]
+1: Any news on when s3curl will be replaced by something that supports IAM roles?

**Comment by jtheuer** [comment]
This requests doesn't seem to attract much attention. Isn't it what most people to - store cookbooks in s3 or do most people not use instance profiles? (Or don't care about the extra user-credentials)?

**Comment by SharpEdgeMarshall** [comment]
Following new best practices we should no longer use Berkshelf with Chef 12 but send a complete package.
I think that more and more people are going to use S3 to store the packaged cookbook, so it would be useful if OpsWorks could use its IAM role to access S3, even because IAM roles have been made for this kind of tasks.
I don't want to have to create a **CookbooksS3ReadOnlyUser**, is much more cleaner to just add a **CookbooksS3ReadOnly** policy to the  **aws-opsworks-service-role**.

**Comment by githuesch** [comment]
This has actually been fixed quite some time ago, but we never got around to resolve this GitHub issue. You can use the IAM role by leaving the fields for Access key ID and Secret access key empty.
