### ISSUE TITLE
conflicting names between opscode community cookbooks and opsworks cookbooks

### ISSUE THREAD

**Issue by dieend** [aws/opsworks-cookbooks#217]
I don't know it's relevant or not, but I think cookbooks in aws-opsworks should used different name with cookbooks from opscode community. For example, opsworks' `php` cookbook should have named `opsworks-php` instead of only `php`.

The arguments for it:
- To differentiate between community maintained cookbook (which obviously what people uses in local)
- Berkshelf doesn't support multiple dependency with same cookbooks name (which obviously should not happen)

I know it might break many people cookbooks, but maybe you can give arguments why opsworks doesn't uses community cookbooks (for example php) and created a custom one with different name. I know in chef 11.10 the community cookbooks merged into the opswork cookbooks in the process, but it doesn't happen in local environment, and IMO it's only a workaround which doesn't go with cookbooks best practice.

Sorry for my rant.

**Comment by dpehrson** [comment]
This is an insanely large problem, I realize this isn't an easy thing to fix, but AWS really needs to not reuse existing community cookbook names. It is not possible to use the community 'mysql' cookbook because of it.

**Comment by dpehrson** [comment]
Just hit this again, can't use the community nginx cookbook because of OpsWorks old/out of date one. This is really getting to the point where I'm not sure I feel comfortable using OpsWorks in production.

**Comment by bratke** [comment]
+1 This affects us too.

**Comment by shlomoswidler** [comment]
Might it be possible to create an insulated environment within an OpsWorks chef-client run that **runs its own** chef-client that uses only the custom cookbooks and their community cookbook dependencies?

**Comment by shlomoswidler** [comment]
Questions for those waiting for a solution to this issue:
Let's say there was a mechanism to create an insulated chef-client run within the OpsWorks chef-client run, and you could specify a custom cookbook source, such as a tarball, or a git repo, for that insulated environment.
1. How important would Berkshelf support be for that insulated environment?
2. Could you live without the ability to persist chef's node state across runs (e.g. node.save would succeed but the state would not actually persist to the next run) of your insulated environment?

**Comment by dieend** [comment]
@shlomoswidler I don't think running chef-client that uses only custom cookbooks (without opsworks cookbooks) is a better solution. Our problem not with OpsWorks using it's own custom cookbooks, but  because some cookbooks conflicted with community cookbooks.

Take for example apache2 cookbooks. Opscode community already have the apache2 cookbook and quite completed. I can't see any reason OpsWorks creating it's own apache2 cookbooks, instead of creating other cookbooks that uses the community apache2 cookbooks.

**Comment by dpehrson** [comment]
@shlomoswidler As @dieend mentioned, I don't think we need to overcomplicate the problem, OpsWorks should just commit to two things:
1. Make an effort when possible to rename existing cookbooks with the same prefix, eg `nginx` to `opsworks-nginx`. My understanding is that breaking changes are only introduced when OpsWorks introduces a new chef version, so perhaps the next that that is done, it would be a good idea.
2. Do not introduce any new cookbooks with names that conflict with community cookbooks, just prefix them with `opsworks-XXX`. To me this is even more important. Right now I've already had to stop using the `nginx` and `mysql` cookbooks because of the naming conflict with OpsWorks, but I have many more defined. If OpsWorks tomorrow were to say introduce a cookbook called `apt` all of my provisioning would break without warning.

**Comment by shlomoswidler** [comment]
@dieend @dpehrson Completely agree, this problem needs to be solved by the AWS OpsWorks team.

However, until they do that, it seems to me that a reasonable workaround is this:
Create an insulated chef-client invocation that is executed as part of the run list for every OpsWorks action (setup, configure, deploy, etc.). This insulated invocation installs its own cookbooks (custom repo, Berkshelf, whatever) and has its own custom run list.

With this workaround, you can use community cookbooks from within the insulated chef-client invocation, without any conflicts with the AWS opsworks-cookbooks. Any of your own custom recipes that need the community cookbooks can be called from within the insulated chef-client invocation.

I have a working (but still in-progress) implementation of this. Anyone who is interested: Please let me know.

**Comment by shlomoswidler** [comment]
Here is an early version of this implementation:

https://github.com/shlomoswidler/tabula_rasa

Run community cookbooks from within AWS OpsWorks without clashing with the older versions in opsworks-cookbooks. Recipes run from within Tabula Rasa will not have access to the opsworks-cookbooks (unless you include them in your repository) but they will see your Custom Stack JSON and all the Ohai settings added by the AWS OpsWorks Agent.

Version 0.1.0 has only been tested with Chef 11.10, on Ubuntu 12.04, and only supports Git and SVN repositories.

This won't prevent OpsWorks recipes from running, but it will give you an isolated environment in which you can run community cookbooks without worrying about the name and version conflicts with opsworks-cookbooks.

**Comment by shrinathaithal** [comment]
+1, would like to have these renamed too...

**Comment by aik099** [comment]
I'm not having this issue yet, but :+1: for using opsworks unique cookbook names to solve conflicts with community cookbooks.

**Comment by ainame** [comment]
:+1:

I want to use nginx of community cookbooks, but opsworks have a very careless merging process for custom cookbooks. So, I'm unwilling to use that way, it's unreliable.
It is not limited to this problem, can opsworks make more better merging solution?

https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/opsworks_custom_cookbooks/recipes/load.rb#L12-L18

I will hope to improve this problem. :pray:

**Comment by bassrock** [comment]
I am having the same issue with the community nodejs cookbook as I want to use nodejs_npm

**Comment by corycomer** [comment]
Ran into this a couple of times now, nginx, php, and mysql cookbooks specifically. This is indeed very annoying. I can imagine it would be difficult to rename some of the cookbooks because there's probably a lot of people referencing them by now. Maybe if their merge solution checked for a cookbook in the custom repo or defined in a Berksfile that would supercede the opsworks cookbook, and when nothing is found it just defaults to the opsworks one would be a solution. Keeps backwards compatibility for people using the existing cookbooks, but provides a sort of "caveat emptor" for anyone wanting to override one of the defaults; if you don't implement something that another cookbook is using, don't come a crying, etc... /shrug

Looking at https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/opsworks_custom_cookbooks/recipes/load.rb#L12-L18 seems like you could re-order the merge process or iterate through and exclude the defaults after the site cookbooks and berksfile stuff has been merged, giving the custom cookbooks a high precedence with the defaults as a fallback.

**Comment by Whitespace** [comment]
Please give us an option to opt-out of pulling in these opsworks cookbooks.  Never would I think to look in this repo for a cookbook for nginx when the overwhelming majority of the chef universe knows to look at supermarket first.

The current way that OpsWorks operated in wrt cookbooks should be considered quirksmode, because cookbooks that work locally no longer work in opsworks.

**Comment by fred** [comment]
+1 on this issue, it's nearly impossible to use anything from community cookbooks.
I think AWS want to lock users on using their cookbooks and RDS, if can't use mysql cookbook, no problem, use RDS.
Other than that the only reason I see for using this naming convention is that it was not well thought by opsworks developers, and now it's too large of a codebase to change.

This definitely needs to be addressed by AWS.

**Comment by yogin** [comment]
:+1: Also hitting this issue, trying to use some community cookbook which has a dependency on nginx ... and then conflicts with the version in opsworks!

**Comment by azhurbilo** [comment]
+1

**Comment by firon** [comment]
+1
I'm having this problem since the nginx cookbook included here _overrides_ attributes from the official nginx cookbook that I specified in my Berksfile.

**Comment by bbc88ks** [comment]
+1

**Comment by bbergstrom** [comment]
+1

**Comment by christopher5106** [comment]
+1

**Comment by gkaemmer** [comment]
+1. Any community cookbook that depends on `apache2 >= 2.0` causes a dependency problem.

**Comment by nickjwebb** [comment]
+1, opsworks naming is making things way more complicated then they need to be.

**Comment by vjm** [comment]
+1

**Comment by jshthornton** [comment]
+1

**Comment by sverdier** [comment]
+1

**Comment by rsutton1** [comment]
+1

**Comment by fred** [comment]
AWS will never rename the cookbooks. it's not possible.
so why dont we just close this issue and move on.

**Comment by sverdier** [comment]
Why ? everything is possible...

**Comment by rsutton1** [comment]
Why can't they just add an option to disable OpsWorks default cookbooks...

**Comment by cb-sivalingams** [comment]
:thumbsup: its nice, if they provide option to disable default Opsworks cookbooks

**Comment by jcderose** [comment]
+1, we're running into this too.

**Comment by ljay79** [comment]
+1

**Comment by melechi** [comment]
+1

**Comment by digitalbase** [comment]
+1

**Comment by kn0ll** [comment]
the docs suggest that berkshelf cookbooks will take precedent when merged into built in cookbooks. that doesn't seem to be the case though, at least for all files.

for instance, once i update my custom cookbooks, /var/lib/aws/opsworks/cache.stage2/cookbooks/php/recipes/source.rb contains the recipe from the community php library. but /var/lib/aws/opsworks/cache.stage2/cookbooks/php/metadata.rb is from the built in library, which forces the recipe to fail.

i'd consider using the built in library, except it _doesn't actually even install_ PHP _despite it's description_. lol?

**Comment by danapplegate** [comment]
+1. Over a year after the issue was first submitted, and silence from Amazon and the OpsWorks team in the interim? This does not bode well for future support of Custom layers in OpsWorks, and does little to boost my confidence in the service as a whole.

What have other people in this thread done to work around the issue? I presume that, given the age of the issue, folks have either come up with a workaround, or given up entirely and switched to something other than OpsWorks?

**Comment by nickjwebb** [comment]
@danapplegate we use https://github.com/shlomoswidler/tabula_rasa

It is a bit of a hack, but it works. It really takes a lot of extra time to work within that framework, though. We looked at improving it further, but got pretty frustrated trying to learn a lot of obscure stuff that's required to truly contribute... we gave up as we heard the OpsWorks team is fixing this with Chef 12 which is already available for OpsWorks on Windows.

Per talk at re:Invent 2015 (early October), this Chef 12 based release is expected "soon" for Linux, pending documentation updates (including documentation on how to upgrade from 11.x to 12).

I feel your pain here, though, even with tabula_rasa I'm tempted every other day to move to stand alone chef servers; but I'm giving the OpsWorks team until 1/1/2016 to release this as it would simplify things for us. I'm hopeful 1/1/2016 will be hit, but really no one other than AWS knows where that sits.

**Comment by jweiss** [comment]
In the upcoming Chef 12 release, we have two distinct Chef runs, one for the core/minimal OpsWorks setup and one for your cookbooks. The second run has no cookbooks but your own, so there will be no naming conflict.

If you want to use Chef 12 today, please ping me for access to the beta.

**Comment by dieend** [comment]
@jweiss I'm in for beta. A lot of cookbook nowadays drop support for chef 11, and every month our CI broke because of breaking changes they introduces. Do I need to share our aws account id, or what?

**Comment by jweiss** [comment]
Yes, I would need your AWS account ID. Please send it to chef-12-beta at my company's email (amazon).

**Comment by dmerrick** [comment]
Awesome, @jweiss! I sent an email.

**Comment by githuesch** [comment]
We just completed the "upcoming Chef 12 release" @jweiss mentioned. Please check out [our launch announcement](https://forums.aws.amazon.com/ann.jspa?annID=3397).
