### ISSUE TITLE
mod_php5_apache2 web_app template fails if no environment variables specified

### ISSUE THREAD

**Issue by bbc88ks** [aws/opsworks-cookbooks#270]
When setting up **mod_php5_apache2** on an instance, it tries to render a template:
## Compiled Resource:
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/apache2/definitions/web_app.rb:29:in `block in from_file'

template("/etc/apache2/sites-available/applet_skeleton.conf") do
params {:template=>"web_app.conf.erb", :local=>false, :enable=>true, :docroot=>"/srv/www/applet_skeleton/current/", :server_name=>"applet_skeleton", :mounted_at=>nil, :ssl_certificate_ca=>nil, :name=>"applet_skeleton"}
provider Chef::Provider::Template
action "create"
retries 0
retry_delay 2
path "/etc/apache2/sites-available/applet_skeleton.conf"
backup 5
atomic_update true
source "web_app.conf.erb"
variables {:application_name=>"applet_skeleton", :params=>{:template=>"web_app.conf.erb", :local=>false, :enable=>true, :docroot=>"/srv/www/applet_skeleton/current/", :server_name=>"applet_skeleton", :mounted_at=>nil, :ssl_certificate_ca=>nil, :name=>"applet_skeleton"}}
cookbook_name "mod_php5_apache2"
recipe_name "php"
mode "0644"
owner "root"
group "root"
end

So in the template we have:
![image](https://cloud.githubusercontent.com/assets/3134014/5880549/0f7bb440-a342-11e4-8050-5035ace324c1.png)

Which gets populated from:
![image](https://cloud.githubusercontent.com/assets/3134014/5880591/50dab706-a342-11e4-879c-79fec99270b6.png)

If no environment variables provided for app it would fail to render a template.

**Comment by bbc88ks** [comment]
This affects all PHP Layer stack instances with Chef 11.10

**Comment by masom** [comment]
Yep, we just got hit by this and we currently can't deploy.

**Comment by saidababuchanda** [comment]
Hi All,

This is an issue if you are using Berksfile in OpsWorks and the Berksfile has dependencies on apache2 cookbook pulled from super market.

ex:: if your Berksfile has a dependency like below::

#!/usr/bin/env ruby
-- encoding : utf-8 --

source "https://api.berkshelf.com"
eset/metadata

cookbook 'mongodb'
cookbook 'mod_security'

Here, if you look at mod_security dependencies here:: https://supermarket.chef.io/cookbooks/mod_security#dependencies

It depends on

apache2 >= 0.0.0
build-essential >= 0.0.0

You see apache2 there, and OpsWorks also has cookbook with the same name, so the problem is you are overriding the OpsWorks cookbook with apache2 cookbook from supermarket and its causing the issue.

Solution::
1.  avoid dependencies which installs conflicting cookbooks with OpsWorks.
