### ISSUE TITLE
io.js support and/or node 12.x support?

### ISSUE THREAD

**Issue by Torsph** [aws/opsworks-cookbooks#302]
Do you have any time frame on when you will support io.js or node version 12.x?

Or is it possible to do get a newer version of node with custom json?

Thanks!

**Comment by Mickael-van-der-Beek** [comment]
Any news on this front ?

**Comment by IanVS** [comment]
I would also like to know what is the plan for node.js on AWS.  `0.10.38` is very old, and my app relies on the newer ES6 features that are gained with io.js and node 0.12.  I found an older guide at https://forums.aws.amazon.com/message.jspa?messageID=495060, but it no longer seems to work (I believe the recipe has changed since it was written, and I can't figure out how to override the repository the .deb is pulled from).

**Comment by alexmsmartins** [comment]
I have this bug https://github.com/nodejs/io.js/issues/712 while using nodejs in an application that runs in AWS.

Io.js fixes it. 

Is there a timeframe for having access to io.js in AWS? Otherwise, we will not be able to use SSL. Which might be a show stopper for using AWS.

Thanks

**Comment by mitchross** [comment]
I am also requesting NodeJS 12.X as there is a major security flaw in older versions.

**Comment by felixdulfer** [comment]
+1 for ES6/iojs

**Comment by ashwinks** [comment]
+1 for at least .12 support

**Comment by jweiss** [comment]
Node.js 0.12.7 is available through the UI and API

**Comment by tusharmath** [comment]
IO.js is still not supported?
