### ISSUE TITLE
git-core package sometimes stops installing properly

### ISSUE THREAD

**Issue by ajsharp** [aws/opsworks-cookbooks#311]
I've seen this happen on two instances now, and once it starts happening, it keeps happening, and I have to get rid of the instance. Here is the full chef log output:

```
[2015-06-10T19:59:14+00:00] INFO: Starting chef-zero on port 8889 with repository at repository at /opt/aws/opsworks/current
One version per cookbook
data_bags at /var/lib/aws/opsworks/data/data_bags
nodes at /var/lib/aws/opsworks/data/nodes

[2015-06-10T19:59:14+00:00] INFO: Forking chef instance to converge...
[2015-06-10T19:59:14+00:00] INFO: *** Chef 11.10.4 ***
[2015-06-10T19:59:14+00:00] INFO: Chef-client pid: 22669
[2015-06-10T19:59:15+00:00] INFO: Setting the run_list to ["opsworks_custom_cookbooks::load", "opsworks_custom_cookbooks::execute"] from JSON
[2015-06-10T19:59:15+00:00] WARN: Run List override has been provided.
[2015-06-10T19:59:15+00:00] WARN: Original Run List: [recipe[opsworks_custom_cookbooks::load], recipe[opsworks_custom_cookbooks::execute]]
[2015-06-10T19:59:15+00:00] WARN: Overridden Run List: [recipe[opsworks_custom_cookbooks::load], recipe[opsworks_custom_cookbooks::execute]]
[2015-06-10T19:59:15+00:00] INFO: Run List is [recipe[opsworks_custom_cookbooks::load], recipe[opsworks_custom_cookbooks::execute]]
[2015-06-10T19:59:15+00:00] INFO: Run List expands to [opsworks_custom_cookbooks::load, opsworks_custom_cookbooks::execute]
[2015-06-10T19:59:15+00:00] INFO: Starting Chef Run for rails-app3.localdomain
[2015-06-10T19:59:15+00:00] INFO: Running start handlers
[2015-06-10T19:59:15+00:00] INFO: Start handlers complete.
[2015-06-10T19:59:15+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: /reports/nodes/rails-app3.localdomain/runs
[2015-06-10T19:59:22+00:00] INFO: Loading cookbooks [apache2, dependencies, deploy, gem_support, mod_php5_apache2, mysql, nginx, opsworks_agent_monit, opsworks_aws_flow_ruby, opsworks_berkshelf, opsworks_bundler, opsworks_commons, opsworks_custom_cookbooks, opsworks_initial_setup, opsworks_java, opsworks_nodejs, opsworks_rubygems, packages, passenger_apache2, php, rails, ruby, scm_helper, ssh_users, unicorn]
[2015-06-10T19:59:23+00:00] INFO: Not needed with Chef 11.x (x >= 8) anymore.
[2015-06-10T19:59:23+00:00] INFO: Processing package[git-core] action install (opsworks_custom_cookbooks::checkout line 9)

================================================================================
Error executing action `install` on resource 'package[git-core]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '100'
---- Begin output of apt-cache policy git-core ----
STDOUT: 
STDERR: E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_universe_i18n_Translation-en
E: The package lists or status file could not be parsed or opened.
---- End output of apt-cache policy git-core ----
Ran apt-cache policy git-core returned 100


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage1/cookbooks/scm_helper/libraries/package.rb

9:             package "git-core"
10:           else



Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage1/cookbooks/scm_helper/libraries/package.rb:9:in `ensure_scm_package_installed'

package("git-core") do
action :install
retries 0
retry_delay 2
package_name "git-core"
cookbook_name "opsworks_custom_cookbooks"
recipe_name "checkout"
end



[2015-06-10T19:59:24+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-06-10T19:59:24+00:00] ERROR: Running exception handlers
[2015-06-10T19:59:24+00:00] ERROR: Exception handlers complete
[2015-06-10T19:59:24+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage1/chef-stacktrace.out
[2015-06-10T19:59:24+00:00] ERROR: package[git-core] (opsworks_custom_cookbooks::checkout line 9) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-cache policy git-core ----
STDOUT: 
STDERR: E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_universe_i18n_Translation-en
E: The package lists or status file could not be parsed or opened.
---- End output of apt-cache policy git-core ----
Ran apt-cache policy git-core returned 100
[2015-06-10T19:59:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

---
```

**Comment by heffergm** [comment]
You can run apt-get update then re provision to get around it .

**Comment by agrass** [comment]
I had been using opsworks like 3 months without this problems and today appears mysteriously without changing nothing. Anybody knows the reason of this? I solved doing apt-get update as @heffergm says,  but i would like to know if there another way to prevents this in other instance?

**Comment by timsegraves** [comment]
I had the same issue just happen and the `apt-get update` fixed it for me as well.  This happened on the first deploy I ran after changing an SSH key which automatically ran the ssh_users recipe on the instances.  Not sure if that was related or not.

**Comment by parallelepiped** [comment]
Bump

**Comment by suan** [comment]
+1

**Comment by beedub** [comment]
(to anyone else looking for a semi-permanent hacky solution)

We created a custom chef recipe that overwrites `/opt/aws/opsworks/current/cookbooks/scm_helper/libraries/package.rb` on the target host with a version that adds `ignore_failure true` to the `git-core package` to get around these errors. This approach is still subject to its own issues, but it should be a bit more stable

The chef recipe:

```
require 'digest/md5'

filename = "/opt/aws/opsworks/current/cookbooks/scm_helper/libraries/package.rb"
execute "backup old version of package.rb" do
  command "mv #{filename} #{filename}.old"
  only_if { Digest::MD5.hexdigest(File.read(filename)) == "a6b61a2e710c81000ebf64c5f65f723e" }
  notifies :create, "template[#{filename}]", :immediately
end

template(filename) do
  source 'package.rb'
  mode '0440'
  action :nothing
end
```

and the template:

```
# This is a copy of https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/scm_helper/libraries/package.rb
# except for the line commented below
module OpsWorks
  module SCM
    module Package

      def ensure_scm_package_installed(scm_type)
        Chef::Log.info("Running custom package function")
        if scm_type == "git"
          case node[:platform]
          when "debian", "ubuntu"
            package "git-core" do
              # Adding ignore_failure due to https://github.com/aws/opsworks-cookbooks/issues/311
              ignore_failure true
            end
          else
            package "git"
          end
        elsif scm_type == "svn"
          package "subversion"
        elsif scm_type == 'archive' || scm_type == 's3'
          case node[:platform]
          when 'debian', 'ubuntu'
            package 'git-core'
            package 'libdigest-hmac-perl'
          else
            package 'git'
            package 'perl-Digest-HMAC'
          end
          package 'unzip'
        elsif scm_type == 'other'
          Chef::Log.info "scm_type 'other', nothing to install"
        else
          raise "unsupported SCM type #{scm_type}"
        end
      end

    end
  end
end

class Chef::Recipe
  include OpsWorks::SCM::Package
end
```

**Comment by localredhead** [comment]
I found this https://forums.aws.amazon.com/message.jspa?messageID=626424

The steps listed within worked for me:
1. ssh into the box
2. become root
3. `sudo rm /var/lib/apt/lists/* -vf`  (at first this seemed dangerous but ended up being painless)
4. `sudo apt-get update` 

As far as I'm concerned this is the solution.

**Comment by parallelepiped** [comment]
@localredhead Is this solution good for one-time only or does it fix it permanently on that box? Can you use it to immunize future servers as well?

**Comment by dbpolito** [comment]
This also happened to me... There might be a safe way for handling it.

**Comment by LeeSaferite** [comment]
We've had it happen sporadically for months now. Every time we have to log into the box to recover. That is NOT a good solution. Anyone have any idea how to really solve the issue?

**Comment by localredhead** [comment]
@parallelepiped For us it was a one-time solution.

**Comment by ghost** [comment]
Have experienced this issue for months now as well, always easy to fix , however would like a more stable permanent solution. Always seems to be with the exact same file.

/var/lib/apt/lists/us-west-2.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_main_i18n_Translation-en 

I would like to continue to use the aws mirrors , will keep an eye out for an update.

**Comment by kjhangiani** [comment]
Any update on this?  We experience this an extremely non-trivial amount.  We have about 50-60 instances across 4 stacks, and I would say on average, 20% of them will fail with this error when updating cookbooks (which might happen every month or so).  I don't think I've ever run update_custom_cookbooks on 10 instances and not had at least 3 of them fail.

This kills all recipes and completely destroys the purpose of opsworks, which is so that I never have to log into the box.  The machines that experience this issue are not always the same, it's random as far as I can tell.  So far, the only way around this has been to manually log in and `sudo rm -vf /var/lib/apt/lists/*` followed by `sudo apt-get update`.  This does fix the issue, but it's temporary.

Has anyone found a more permanent workaround, or a better alternative?  @beedub I am going to explore your suggestion there, unless you've come up with something better since then.  It's incredibly frustrating having sophisticated deployment recipes that fail which such frequency, for reasons that seem out of my control.

I agree with @gitjoey in that it's always `/var/lib/apt/lists/us-west-2.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_main_i18n_Translation-en`

This is pretty much what it looks like everytime I run update_custom_cookbooks:
![image](https://cloud.githubusercontent.com/assets/917192/14224921/20acd344-f863-11e5-98c4-e9172a858f8c.png)

I actually just browsed through the last few log entries for update_custom_cookbooks and I'm seeing failures of 2 out of 9, 3 out of 8, and 1 out of 5 on various sets.  All on the same list, and seems to be randomly different instances each time.

These are all running identical setups, and are all t2.small or t2.medium instances.  We only have custom recipes on setup, and nothing on configure.

**Comment by lordcoppetti** [comment]
It's been happening to us too for a few months on 2 instances for every deploy we did. Exact same issue.
As mentioned by @localredhead simply doing sudo apt-get update fixes it for one time.
@beedub hacky approach seems to fix it.

**Comment by agolan-amazon** [comment]
We have introduced several improvements around this behavior in agent version 3433 (for Chef 11.10). In order for the enactments to take effect, you would be required to re-provision the instance(s).

Please feel free to approach me directly with additional questions

**Comment by zivagolee** [comment]
@agolan-amazon can you tell us why it requires re-provision? is there no way to just upgrade the agent and just update cookbooks or re-run a setup recipe?

**Comment by kjhangiani** [comment]
@agolan-amazon 3433 is already the version we've been using (that I experienced the issues above in) - has there been changes directly on that branch without a version bump?  I also see 3434 and 3435 now.  Can you confirm that 3433 is all we need for this fix?  Or should I bump up our chef version across the board?

**Comment by parallelepiped** [comment]
Well, at this point I believe my company will be abandoning OpsWorks completely. This problem is one of about a dozen which simply cannot be solved and requires us to ssh in, poke around, email support, etc., and burn about four engineer days a month in useless maintenance. We'll probably switch to Elastic Beanstalk. Has anyone else had this experience?

**Comment by agolan-amazon** [comment]
@kjhangiani @zivagolee We'd be happy to look through these problems, would you be able to open a support ticket with us so that we may involve our engineers?

**Comment by zivagolee** [comment]
@agolan-amazon Submitted case 1727664471. Can you please follow-up with the Opsworks team on this?

**Comment by agolan-amazon** [comment]
Will do, thank you for submitting the case.

**Comment by mlins** [comment]
It's a common/annoying issue we run into as well. I don't think it's really an opsworks issue as much as an ubuntu issue. There is a bug report for it somewhere in launchpad, but I can't find it right now.

I think upgrading to a newer version of ubuntu would fix it, but I haven't tried that yet.

**Comment by kjhangiani** [comment]
@agolan-amazon still experiencing this issue, even on newly provisioned servers.  Instances that I spun up in the last week, on version 3433, are failing with the same error.  Again it's random, but I estimate about 1 in 5 fail.  Just updated 5 servers today with 2 failures.

I will open a ticket shortly through AWS, have to check on our support hours, but just wanted to say that reprovisioning on 3433 absolutely does NOT fix the problem.  The machines that are failing are < 1 week old.  I have not tried using a higher chef version as I did not receive any feedback on whether that would make any difference.

@mlins I agree it's not strictly an opsworks issue, but it makes opsworks completely useless, especially with the frequency it occurs.  This is not a rare occurrence.  It also fails on an amazon-provided list  `/var/lib/apt/lists/us-west-2.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_main_i18n_Translation-en` so I definitely place some responsibility for this on Amazon's shoulders.

**Comment by maciej-zywno** [comment]
I have run a few hundred test deployments today on newly provisioned micro instances for `Ubuntu 14.04 LTS, Chef 11.10, Agent 3437` to see if the issue happens in our environment and all `Processing package[git-core] action install` actions succeeded. Wondering if the issue happened for anyone for the same agent, chef and ubuntu version?

**Comment by kjhangiani** [comment]
@zywy the issue is not every time, it will occur as time goes on.  From my experience, on a particular instance, it might occur once a month or so, but when you have 50 instances, this results in about 10 out of 50 failing every run.  We have nothing running on configure either, but my guess is something related to configure is what breaks it.  You'll know an instance is broken if you look at the activity logs and suddenly see a bunch of failed configures, and update custom cookbooks doesn't work.

**Comment by thomasbaldwin** [comment]
I'm running Amazon Linux 2016.03 with Chef Version 11.10 and started experiencing this error today. I've been using OpsWorks and making deployments successfully for the past 2-3 months before this error occurred out of nowhere today

**Comment by agolan-amazon** [comment]
This is an issue had been identified by Ubuntu and is being worked on. Please see the following reference:
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1406268

**Comment by kjhangiani** [comment]
@agolan-amazon that ticket has been open for years.  There are a number of similar issues on serverfault.  That doesn't excuse the fact that opsworks does not handle this error well at all - it's a simple fix to resolve, and yet it completely blocks deployments.  It literally defeats the entire purpose of using opsworks if I have to manually fix 30% of my deployments every time I run a command.  Once a machine is broken, there is literally no way via opsworks to fix it.  I understand that the issue is due to a bug in ubuntu, but if you guys want opsworks to be useful at all, then this is one of the types of issues that you need to provide a real workaround for, until they do fix it.  

The bug is obviously not a high priority for ubuntu as they are not anticipating that these commands will be run regularly by an automated system such as opsworks - if I manually encounter this bug, it's a trivial fix.  However, for the opsworks usage case, it's critical.  I cannot stress how significant of an impact this bug has on our deployments - we are actually actively moving away from opsworks entirely, solely because of it.

EDIT:
Just ran update_custom_cookbooks on one of our stacks.  Here's what it looks like (edited to remove hostnames for privacy):

<img width="650" alt="blur-clients" src="https://cloud.githubusercontent.com/assets/917192/15763082/4ec14834-28d6-11e6-962c-cce4d8061ac9.png">

Every single one of those I have to manually log into and `sudo rm -vf /var/lib/apt/lists/*` followed by `sudo apt-get update` before anything will work, including the automated configure recipes

**Comment by schollii** [comment]
Same issue arose today out of nowhere and unfortunately doing those 2 steps (rm and update) did not fix the problem, the instance failed to start.
