### ISSUE TITLE
Can't rollback PHP applications

### ISSUE THREAD

**Issue by marpada** [aws/opsworks-cookbooks#315]
The repository lacks a recipe for deploy::php-rollback, so the ability to rollback PHP application is broken by default. Workaround is to add a custom deploy::php-rollback recipe as on https://gist.github.com/marpada/d78adea6480b3ca5264c

**Comment by cosmmin** [comment]
Hi marpada,

I came to the same conclusion as you, only i couldn't find a non-hackish way to add the custom recipe to the rollback run list. My options were: 
- add the custom recipe to the undeploy action and do undeploy instead of rollback
- deploy with a custom JSON that overrides the "action" attribute and sets it to "rollback"

How did you do it? 

Many thanks.

**Comment by et304383** [comment]
How is this a missing feature?  PHP is (unfortunately) the most popular web development framework and Opsworks has no rollback recipe?

How was this missed?  :(
