### ISSUE TITLE
Custom OpsWorks tags

### ISSUE THREAD

**Issue by rnhurt** [aws/opsworks-cookbooks#357]
I would be handy to configure custom tags on OpsWorks resources.  Our team uses tags to show which systems are PROD and which are DEV. the system's emergency contact, and a host of other things.

The idea of using custom JSON as outlined [here](https://github.com/stuart-warren/chef-aws-tag) seems to be pretty compact and would require no new GUI elements on the OpsWorks console.

**Comment by toddlers** [comment]
@rnhurt  We use https://github.com/chef-cookbooks/aws for tagging our resources depending on the stack naming convention.

What I would look forward is just like ec2 instances has tags and we can build  conditional IAM policies using them. Something like that in OpsWorks stacks would help a lot instead of we whitelisting the stack ids in the IAM policies.

**Comment by zanzan42** [comment]
Toddlers, can you clarify how you've gotten this to work under OpsWorks? The stuart-warren/chef-aws-tag cookbood doesn't work under OpsWorks due to a dependency problem with the chef-cookbooks/aws LWRP. There's an issue with how they are using aws-sdk v1 vs. v2 (AWS vs. Aws function calls) causing an "uninitialized constant Aws" error when trying to use the resource_tag LWRP.

See this issue thread on chef-cookbooks/aws:

https://github.com/chef-cookbooks/aws/issues/104

I'd love to figure out a way to fix this, because it's a big problem for a lot of people using OpsWorks.

**Comment by toddlers** [comment]
@zanzan42  this is one example of tagging the instances.

```
 67 aws_resource_tag node['opsworks']['instance']['aws_instance_id'] do
 68   tags({"#{node['escluster']['discovery']['strictly_unique_tag_name']}" => "#{my_cluster_tag}"})
 69   action :update
 70   only_if do node['escluster']['discovery']['auto_discover_type'].eql?("ec2") end
 71 end
```

Following are the env settings 
          cookbook  : https://github.com/chef-cookbooks/aws | "version": "2.5.0",
          OpsWorks : Chef Version 11

added corresponding dependency in the cookbooks's metadata .

**Comment by zanzan42** [comment]
That explains it. The problems with chef-cookbooks/aws started when they moved from right_aws to using the aws-sdk on versions >=2.6.0. The problem doesn’t exist in 2.5.0.

But it does point out that tagging doesn’t appear to require credentials, which means that 2.5.0 should be completely usable if all I’m using it for is tagging. The major feature change going from 2.5.0 to 2.6.0+ was the introduction of IAM profile support, which doesn’t appear to be necessary for tagging.

Thanks,

Allan

**Comment by jweiss** [comment]
We do support tags in OpsWorks: https://aws.amazon.com/blogs/mt/introducing-tagging-support-for-aws-opsworks-stacks/
