### ISSUE TITLE
Apache2 restarts too often

### ISSUE THREAD

**Issue by dcsaszar** [aws/opsworks-cookbooks#75]
Since https://github.com/aws/opsworks-cookbooks/commit/dda66512fedf7077534a951a57291a78d955b151 Apache will be restarted on every `include_recipe "apache2"`.
This may lead to unwanted outages, for instance on Rails Passenger app deployments.

From our deploy log:

```
[Tue, 12 Nov 2013 20:18:40 +0000] INFO: execute[logdir_existence_and_restart_apache2] sending restart action to service[apache2] (delayed)
```

**Comment by mrclmrvn** [comment]
(y)

**Comment by kostia** [comment]
:+1: for a quick fix. You can forget about continuous deployment otherwise...

**Comment by arielpts** [comment]
+1 for this! VERY needed.

**Comment by heffergm** [comment]
There are a number of resources in recipes/default.rb that call 'logdir_existence_and_restart_apache2', none of which should cause a restart unless there are applicable updates (templates, etc). However, the following block exists in the recipe as well, for reasons I can't quite fathom, which ensures that the restart will be called on every run, regardless of whether a restart is otherwise called for or not. Can we dump this block please?

```
bash 'logdir_existence_and_restart_apache2' do
  action :run
end
```

**Comment by awsrequena** [comment]
@heffergm you're right.  None of the 'logdir_existence_and_restart_apache2' calls should apply unless there are applicable updates.

Nonetheless, the last block executing the restart needs to be done, because we currently write the apache logs on a different EBS volume and this is mounted per AutoFS.  We need to 

```
bash 'logdir_existence_and_restart_apache2' do
  action :run
end
```

in order to ensure that there are no overlaying and that we're writing in the right file system.

Currently, we have to go this way.

Thanks everybody for your feedback.
