### ISSUE TITLE
Bug: monit configuration for nodejs apps

### ISSUE THREAD

**Issue by till** [aws/opsworks-cookbooks#83]
The `stop command` seems wrong:

https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/opsworks_nodejs/templates/default/node_web_app.monitrc.erb#L3

Should be wrapped in `/bin/sh -c '...'` as well. At least this doesn't work on precise at all. Monit will report the service is no longer _monitored_, but the service is still running in the background.

Hence, deploys of nodejs apps do not work either since the code is not reloaded.

**Comment by githuesch** [comment]
IIRC, I put the bin/sh -c is in place for the start command because there I have multiple shell commands separated with semicolon and monit didn't accept that. The stop command has just pkill with parameters, but not multiple commands.

I tried this on precise and it works for me. I deployed an app five times with different content each and got different content for every time I retrieved that app. I also see fresh PIDs for the node process after each deployment.

Can you provide more detail about your setup, please?

**Comment by awsrequena** [comment]
no feedback from till , seams fixed or not relevant.
