### ISSUE TITLE
aws-sdk gem for chef runtime is way out of date

### ISSUE THREAD

**Issue by mattbailey** [aws/opsworks-cookbooks#85]
I'd like to have my chef recipes manipulate some opsworks tasks to fill out some templates, but the version installed by opsworks for the chef runtime is pre-opsworks (1.8.1.2). I've tried:

``` ruby
chef_gem "aws-sdk" do
  action [:purge]
  version '1.8.1.2'
end

chef_gem "aws-sdk" do
  action [:install,:upgrade]
  version '1.29.0'
end
```

To no avail.

**Comment by awsrequena** [comment]
The agent is currently using that version of the aws-sdk. This is not pre-opsworks, but very early.

Currently the only way to use a newer version is to install it using "gem_package" instead of "chef_gem".  This will install it on the user space gem area (/usr/local/lib). You'll not be abel to use it directly from Chef but you could use it from external scripts, which you could execute from within a chef recipe.

We're going to update the aws-sdk in a future version of the agent.

**Comment by mattbailey** [comment]
Hmm... Assumed it was pre-opsworks since I get this:

```
NameError: uninitialized constant AWS::OpsWorks
```

From this in a custom cookbook:

``` ruby
require 'aws-sdk'
awscreds = {
  :access_key_id    => node['devproxy']['aws_key'],
  :secret_access_key => node['devproxy']['aws_secret'],
  :region           => 'us-east-1'
}
AWS.config(awscreds)
opsworks = AWS::OpsWorks::Client.new
```

**Comment by githuesch** [comment]
A commit that bumps aws-sdk to 1.32.0 is on its way, should hit production soon.

**Comment by mattbailey** [comment]
Fantastic!

**Comment by awsrequena** [comment]
This is currently running on production.

Thanks for your input

**Comment by mattbailey** [comment]
Great! Much appreciated!
